import { IntrospectionType } from 'graphql';
import { Connection, DataResolver, DataResolverInputHook, DataResolverOutputHook, Features, FortuneOptions } from './GraphQLGenieInterfaces';
export default class FortuneGraph implements DataResolver {
    private fortuneOptions;
    private fortuneTypeNames;
    private uniqueIndexes;
    private schemaInfo;
    private inputHooks;
    private outputHooks;
    private store;
    constructor(fortuneOptions: FortuneOptions, schemaInfo: IntrospectionType[]);
    private getReturnResults;
    private getFortuneIds;
    private computeReturnId;
    getFortuneId: (inputId: string) => string;
    private getTypeFromId;
    getValueByUnique: (returnTypeName: string, args: any) => Promise<Object>;
    canAdd: (graphQLTypeName: string, inputRecords: object[]) => Promise<boolean>;
    getConnection: (allEdges: any[], before: string, after: string, first: number, last: number) => Connection;
    private edgesToReturn;
    private applyCursorsToEdges;
    private getDataTypeName(graphQLTypeName);
    create: (graphQLTypeName: string, records: any, include?: any, meta?: any) => Promise<any>;
    find: (graphQLTypeName: string, ids?: string[], options?: any, include?: any, meta?: any) => Promise<any[]>;
    update: (graphQLTypeName: string, records: any, meta?: any, options?: object) => Promise<any>;
    delete: (graphQLTypeName: string, ids?: string[], meta?: any) => Promise<boolean>;
    private generateCreateRecords;
    private generateUpdates;
    getLink: (graphQLTypeName: string, field: string) => string;
    getStore: () => any;
    private computeFortuneTypeNames;
    getFortuneTypeName: (name: string) => string;
    private buildFortune;
    private inputHook(_fortuneType);
    private outputHook(_fortuneType);
    getFeatures(): Features;
    private generateOptions;
    applyOptions(graphQLTypeName: string, records: any, options: any, meta?: any): any;
    addOutputHook(graphQLTypeName: string, hook: DataResolverOutputHook): void;
    addInputHook(graphQLTypeName: string, hook: DataResolverInputHook): void;
}
